import 'package:fl_valrn/model/recent_model.dart';

final List<RecentItems> dummyRecent =[
  RecentItems(
    title: "Bawang Merah",
    imageUrl: 'https://i.pinimg.com/736x/b7/af/94/b7af94f4aaffab91c65a0b3b64d9e077.jpg', 
    subtitle: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi tempus, tortor et tempus faucibus, sapien magna fringilla ex, non tincidunt nulla neque non dui. Sed fringilla accumsan nisl, at maximus augue consequat eu. Nullam eget lorem lacus. Sed neque elit, efficitur eget neque non, laoreet tincidunt tortor. Suspendisse maximus dui eu nulla sagittis scelerisque. Aliquam urna nisi, euismod non semper vel, dignissim ut massa. Suspendisse vestibulum mollis neque eget tempus. Curabitur auctor eu turpis vel ullamcorper. Etiam eget nisl facilisis, cursus nibh tempus, elementum sapien. Donec molestie odio sed pretium eleifend. Etiam vitae enim nisl. Praesent turpis quam, tempus vel bibendum vitae, semper vel neque. Phasellus viverra vitae ex ut efficitur."),
  RecentItems(title: "Bawang Putih", subtitle: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi tempus, tortor et tempus faucibus, sapien magna fringilla ex, non tincidunt nulla neque non dui. Sed fringilla accumsan nisl, at maximus augue consequat eu. Nullam eget lorem lacus. Sed neque elit, efficitur eget neque non, laoreet tincidunt tortor. Suspendisse maximus dui eu nulla sagittis scelerisque. Aliquam urna nisi, euismod non semper vel, dignissim ut massa. Suspendisse vestibulum mollis neque eget tempus. Curabitur auctor eu turpis vel ullamcorper. Etiam eget nisl facilisis, cursus nibh tempus, elementum sapien. Donec molestie odio sed pretium eleifend. Etiam vitae enim nisl. Praesent turpis quam, tempus vel bibendum vitae, semper vel neque. Phasellus viverra vitae ex ut efficitur.", imageUrl: 'https://i.pinimg.com/736x/b7/af/94/b7af94f4aaffab91c65a0b3b64d9e077.jpg'),
  RecentItems(title: "Daun Bawang", subtitle: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi tempus, tortor et tempus faucibus, sapien magna fringilla ex, non tincidunt nulla neque non dui. Sed fringilla accumsan nisl, at maximus augue consequat eu. Nullam eget lorem lacus. Sed neque elit, efficitur eget neque non, laoreet tincidunt tortor. Suspendisse maximus dui eu nulla sagittis scelerisque. Aliquam urna nisi, euismod non semper vel, dignissim ut massa. Suspendisse vestibulum mollis neque eget tempus. Curabitur auctor eu turpis vel ullamcorper. Etiam eget nisl facilisis, cursus nibh tempus, elementum sapien. Donec molestie odio sed pretium eleifend. Etiam vitae enim nisl. Praesent turpis quam, tempus vel bibendum vitae, semper vel neque. Phasellus viverra vitae ex ut efficitur.",imageUrl: 'https://i.pinimg.com/736x/b7/af/94/b7af94f4aaffab91c65a0b3b64d9e077.jpg'),

];